name: Stylelint-scss


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-scss-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check errors and enforce conventions
        run: |
          npm install --save-dev stylelint stylelint-config-standard-scss
          npx stylelint "**/*.scss"